use std::collections::HashMap;
use std::sync::Mutex;
use std::time::{Duration, Instant};

use uuid::Uuid;

use crate::crypto::VaultKey;
use crate::error::{AppError, AppResult};

/// Default auto-lock delay. Exposed as a constant for now; wiring it to the
/// settings screen is tracked as follow-up work.
pub const AUTO_LOCK_TIMEOUT: Duration = Duration::from_secs(5 * 60);

/// Failed attempts allowed before any lockout kicks in — enough that a
/// mistyped password doesn't punish a legitimate user.
const FREE_ATTEMPTS: u32 = 4;
/// Lockout after the first attempt past `FREE_ATTEMPTS`, doubling with each
/// subsequent failure and capped at `MAX_LOCKOUT`.
const BASE_LOCKOUT_SECS: u64 = 5;
const MAX_LOCKOUT_SECS: u64 = 5 * 60;

/// Tracks failed unlock attempts (master password, TOTP code, or recovery
/// code — they all gate the same login) for a single vault. In-memory only:
/// resets on app restart. This does not stop an offline attacker who copies
/// the vault directory and brute-forces Argon2id directly — nothing running
/// inside the app can prevent that — but it stops guessing through the UI
/// against a session where the vault directory itself stays out of reach.
#[derive(Default)]
struct AttemptTracker {
    failed_count: u32,
    locked_until: Option<Instant>,
}

/// An unlocked vault's key, held only in memory for the lifetime of the
/// session. Dropped (and zeroized, via `VaultKey`) on lock, timeout, or app
/// exit — never written to disk.
struct UnlockedSession {
    dek: VaultKey,
    last_activity: Instant,
}

#[derive(Default)]
pub struct AppState {
    /// Fully authenticated sessions (password, and TOTP if enabled).
    sessions: Mutex<HashMap<Uuid, UnlockedSession>>,
    /// Password verified but awaiting a TOTP code before the session above
    /// is created. Not subject to auto-lock (login itself should not time out
    /// mid-2FA in a way that silently discards the DEK); cleared on success,
    /// failure, or a fresh `unlock_vault` call.
    pending_totp_unlock: Mutex<HashMap<Uuid, VaultKey>>,
    /// Secret generated by `setup_totp` awaiting confirmation via a valid
    /// code before it is persisted to the vault's metadata.
    pending_totp_setup: Mutex<HashMap<Uuid, String>>,
    /// Rate-limiting state for login attempts, keyed by vault.
    attempts: Mutex<HashMap<Uuid, AttemptTracker>>,
}

impl AppState {
    pub fn begin_totp_unlock(&self, vault_id: Uuid, dek: VaultKey) {
        self.pending_totp_unlock.lock().unwrap().insert(vault_id, dek);
    }

    pub fn peek_pending_totp_unlock(&self, vault_id: Uuid) -> AppResult<VaultKey> {
        self.pending_totp_unlock
            .lock()
            .unwrap()
            .get(&vault_id)
            .cloned()
            .ok_or(AppError::VaultLocked)
    }

    pub fn complete_totp_unlock(&self, vault_id: Uuid) -> AppResult<()> {
        let dek = self
            .pending_totp_unlock
            .lock()
            .unwrap()
            .remove(&vault_id)
            .ok_or(AppError::VaultLocked)?;
        self.sessions.lock().unwrap().insert(
            vault_id,
            UnlockedSession {
                dek,
                last_activity: Instant::now(),
            },
        );
        Ok(())
    }

    pub fn open_session(&self, vault_id: Uuid, dek: VaultKey) {
        self.sessions.lock().unwrap().insert(
            vault_id,
            UnlockedSession {
                dek,
                last_activity: Instant::now(),
            },
        );
    }

    pub fn start_totp_setup(&self, vault_id: Uuid, secret_base32: String) {
        self.pending_totp_setup
            .lock()
            .unwrap()
            .insert(vault_id, secret_base32);
    }

    pub fn take_totp_setup(&self, vault_id: Uuid) -> AppResult<String> {
        self.pending_totp_setup
            .lock()
            .unwrap()
            .remove(&vault_id)
            .ok_or(AppError::TotpNotEnabled)
    }

    /// Returns the vault's DEK if it has an active, non-expired session,
    /// bumping its activity timestamp. Lazily evicts and reports as locked
    /// if the auto-lock timeout has elapsed.
    pub fn get_active_dek(&self, vault_id: Uuid) -> AppResult<VaultKey> {
        let mut sessions = self.sessions.lock().unwrap();
        let Some(session) = sessions.get_mut(&vault_id) else {
            return Err(AppError::VaultLocked);
        };
        if session.last_activity.elapsed() > AUTO_LOCK_TIMEOUT {
            sessions.remove(&vault_id);
            return Err(AppError::VaultLocked);
        }
        session.last_activity = Instant::now();
        Ok(session.dek.clone())
    }

    pub fn is_unlocked(&self, vault_id: Uuid) -> bool {
        self.get_active_dek(vault_id).is_ok()
    }

    pub fn lock_vault(&self, vault_id: Uuid) {
        self.sessions.lock().unwrap().remove(&vault_id);
        self.pending_totp_unlock.lock().unwrap().remove(&vault_id);
        self.pending_totp_setup.lock().unwrap().remove(&vault_id);
    }

    pub fn lock_all(&self) {
        self.sessions.lock().unwrap().clear();
        self.pending_totp_unlock.lock().unwrap().clear();
        self.pending_totp_setup.lock().unwrap().clear();
    }

    /// Rejects the attempt outright if the vault is currently locked out
    /// from prior failures. Callers must check this before verifying a
    /// password, TOTP code, or recovery code.
    pub fn check_rate_limit(&self, vault_id: Uuid) -> AppResult<()> {
        let attempts = self.attempts.lock().unwrap();
        if let Some(tracker) = attempts.get(&vault_id) {
            if let Some(until) = tracker.locked_until {
                let now = Instant::now();
                if now < until {
                    return Err(AppError::TooManyAttempts((until - now).as_secs().max(1)));
                }
            }
        }
        Ok(())
    }

    /// Records a failed login step and, past the free-attempt allowance,
    /// locks the vault out for an exponentially growing delay.
    pub fn record_failed_attempt(&self, vault_id: Uuid) {
        let mut attempts = self.attempts.lock().unwrap();
        let tracker = attempts.entry(vault_id).or_default();
        tracker.failed_count += 1;
        if tracker.failed_count > FREE_ATTEMPTS {
            let exponent = (tracker.failed_count - FREE_ATTEMPTS - 1).min(10);
            let delay_secs = BASE_LOCKOUT_SECS
                .saturating_mul(1u64 << exponent)
                .min(MAX_LOCKOUT_SECS);
            tracker.locked_until = Some(Instant::now() + Duration::from_secs(delay_secs));
        }
    }

    /// Clears rate-limit state for a vault after a fully successful login.
    pub fn record_successful_attempt(&self, vault_id: Uuid) {
        self.attempts.lock().unwrap().remove(&vault_id);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn free_attempts_do_not_trigger_a_lockout() {
        let state = AppState::default();
        let vault_id = Uuid::new_v4();
        for _ in 0..FREE_ATTEMPTS {
            state.record_failed_attempt(vault_id);
            assert!(state.check_rate_limit(vault_id).is_ok());
        }
    }

    #[test]
    fn the_attempt_past_the_free_allowance_locks_the_vault_out() {
        let state = AppState::default();
        let vault_id = Uuid::new_v4();
        for _ in 0..FREE_ATTEMPTS + 1 {
            state.record_failed_attempt(vault_id);
        }
        let err = state.check_rate_limit(vault_id).unwrap_err();
        assert!(matches!(err, AppError::TooManyAttempts(secs) if secs > 0));
    }

    #[test]
    fn a_lockout_only_applies_to_the_vault_that_failed() {
        let state = AppState::default();
        let locked_out = Uuid::new_v4();
        let other = Uuid::new_v4();
        for _ in 0..FREE_ATTEMPTS + 1 {
            state.record_failed_attempt(locked_out);
        }
        assert!(state.check_rate_limit(locked_out).is_err());
        assert!(state.check_rate_limit(other).is_ok());
    }

    #[test]
    fn a_successful_attempt_clears_the_lockout() {
        let state = AppState::default();
        let vault_id = Uuid::new_v4();
        for _ in 0..FREE_ATTEMPTS + 1 {
            state.record_failed_attempt(vault_id);
        }
        assert!(state.check_rate_limit(vault_id).is_err());
        state.record_successful_attempt(vault_id);
        assert!(state.check_rate_limit(vault_id).is_ok());
    }

    #[test]
    fn repeated_failures_grow_the_lockout_delay() {
        let state = AppState::default();
        let vault_id = Uuid::new_v4();
        for _ in 0..FREE_ATTEMPTS + 1 {
            state.record_failed_attempt(vault_id);
        }
        let first_delay = match state.check_rate_limit(vault_id).unwrap_err() {
            AppError::TooManyAttempts(secs) => secs,
            other => panic!("expected TooManyAttempts, got {other:?}"),
        };

        // Force the tracker past its own lockout so the next failure is
        // recorded as a fresh escalation rather than being short-circuited.
        state
            .attempts
            .lock()
            .unwrap()
            .get_mut(&vault_id)
            .unwrap()
            .locked_until = Some(Instant::now());
        state.record_failed_attempt(vault_id);

        let second_delay = match state.check_rate_limit(vault_id).unwrap_err() {
            AppError::TooManyAttempts(secs) => secs,
            other => panic!("expected TooManyAttempts, got {other:?}"),
        };
        assert!(second_delay > first_delay);
    }
}
