use std::collections::HashMap;
use std::sync::Mutex;
use std::time::{Duration, Instant};

use uuid::Uuid;

use crate::crypto::VaultKey;
use crate::error::{AppError, AppResult};

/// Default auto-lock delay. Exposed as a constant for now; wiring it to the
/// settings screen is tracked as follow-up work.
pub const AUTO_LOCK_TIMEOUT: Duration = Duration::from_secs(5 * 60);

/// An unlocked vault's key, held only in memory for the lifetime of the
/// session. Dropped (and zeroized, via `VaultKey`) on lock, timeout, or app
/// exit — never written to disk.
struct UnlockedSession {
    dek: VaultKey,
    last_activity: Instant,
}

#[derive(Default)]
pub struct AppState {
    /// Fully authenticated sessions (password, and TOTP if enabled).
    sessions: Mutex<HashMap<Uuid, UnlockedSession>>,
    /// Password verified but awaiting a TOTP code before the session above
    /// is created. Not subject to auto-lock (login itself should not time out
    /// mid-2FA in a way that silently discards the DEK); cleared on success,
    /// failure, or a fresh `unlock_vault` call.
    pending_totp_unlock: Mutex<HashMap<Uuid, VaultKey>>,
    /// Secret generated by `setup_totp` awaiting confirmation via a valid
    /// code before it is persisted to the vault's metadata.
    pending_totp_setup: Mutex<HashMap<Uuid, String>>,
}

impl AppState {
    pub fn begin_totp_unlock(&self, vault_id: Uuid, dek: VaultKey) {
        self.pending_totp_unlock.lock().unwrap().insert(vault_id, dek);
    }

    pub fn peek_pending_totp_unlock(&self, vault_id: Uuid) -> AppResult<VaultKey> {
        self.pending_totp_unlock
            .lock()
            .unwrap()
            .get(&vault_id)
            .cloned()
            .ok_or(AppError::VaultLocked)
    }

    pub fn complete_totp_unlock(&self, vault_id: Uuid) -> AppResult<()> {
        let dek = self
            .pending_totp_unlock
            .lock()
            .unwrap()
            .remove(&vault_id)
            .ok_or(AppError::VaultLocked)?;
        self.sessions.lock().unwrap().insert(
            vault_id,
            UnlockedSession {
                dek,
                last_activity: Instant::now(),
            },
        );
        Ok(())
    }

    pub fn open_session(&self, vault_id: Uuid, dek: VaultKey) {
        self.sessions.lock().unwrap().insert(
            vault_id,
            UnlockedSession {
                dek,
                last_activity: Instant::now(),
            },
        );
    }

    pub fn start_totp_setup(&self, vault_id: Uuid, secret_base32: String) {
        self.pending_totp_setup
            .lock()
            .unwrap()
            .insert(vault_id, secret_base32);
    }

    pub fn take_totp_setup(&self, vault_id: Uuid) -> AppResult<String> {
        self.pending_totp_setup
            .lock()
            .unwrap()
            .remove(&vault_id)
            .ok_or(AppError::TotpNotEnabled)
    }

    /// Returns the vault's DEK if it has an active, non-expired session,
    /// bumping its activity timestamp. Lazily evicts and reports as locked
    /// if the auto-lock timeout has elapsed.
    pub fn get_active_dek(&self, vault_id: Uuid) -> AppResult<VaultKey> {
        let mut sessions = self.sessions.lock().unwrap();
        let Some(session) = sessions.get_mut(&vault_id) else {
            return Err(AppError::VaultLocked);
        };
        if session.last_activity.elapsed() > AUTO_LOCK_TIMEOUT {
            sessions.remove(&vault_id);
            return Err(AppError::VaultLocked);
        }
        session.last_activity = Instant::now();
        Ok(session.dek.clone())
    }

    pub fn is_unlocked(&self, vault_id: Uuid) -> bool {
        self.get_active_dek(vault_id).is_ok()
    }

    pub fn lock_vault(&self, vault_id: Uuid) {
        self.sessions.lock().unwrap().remove(&vault_id);
        self.pending_totp_unlock.lock().unwrap().remove(&vault_id);
        self.pending_totp_setup.lock().unwrap().remove(&vault_id);
    }

    pub fn lock_all(&self) {
        self.sessions.lock().unwrap().clear();
        self.pending_totp_unlock.lock().unwrap().clear();
        self.pending_totp_setup.lock().unwrap().clear();
    }
}
